# Generated by Django 5.1.7 on 2025-04-01 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('D', models.IntegerField()),
                ('M', models.IntegerField()),
                ('Y', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Temp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Morn', models.IntegerField()),
                ('Noon', models.IntegerField()),
                ('Night', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='day', to='wetherprog.date')),
                ('temp', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='day', to='wetherprog.temp')),
            ],
        ),
    ]
